%% Code to generate unformatted version of Figure 3 in Ajuwon et al. 2022
% GoFish: A low-cost, open-source platform for closed-loop behavioural experiments on fish
% Tiago Monteiro 2022

% Get Figure 3 panels' data from excel source data file (Data file 1. “Figure3.xlsx”)
panelA = readmatrix('Figure3.xlsx', 'Sheet','panelA');
panelB = readmatrix('Figure3.xlsx', 'Sheet','panelB');
panelC = readmatrix('Figure3.xlsx', 'Sheet','panelC');
panelD = readmatrix('Figure3.xlsx', 'Sheet','panelD');
panelE = readmatrix('Figure3.xlsx', 'Sheet','panelE');

% make figure
% panel A left
f=figure('name','Figure 3_unformated - Ajuwon et al. (2022)');
f.Position = [100 100 1000 1200]
subplot(3,3,1)
hold on
text(-.01, 1.1, 'A.','fontsize',32)
plot([0.5 12.5],[.5 .5],'--k','linewidth',1.5,'handlevisibility','off')
plot(panelA(1:5,:),...
    ':o','Color',[.5 .5 .5],...
    'linewidth',1,...
    'markerfacecolor',[.5 .5 .5],...
    'markeredgecolor','w',...
    'markersize',10)

plot(mean(panelA(1:5,:),2),'-o','Color','k','HandleVisibility','off',...
    'linewidth',2.5,...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',15)

ylim([0 1])
xlim([.5 5.5])

set(gca,...
    'tickdir','out',...
    'layer','top',...
    'box','off',...
    'linewidth',2,...
    'fontsize',14);
xlabel('Session','fontsize',16)
ylabel('Correct choices', 'fontsize',16) 

% panel A right
subplot(3,3,[2:3])
plot([0.5 7.5],[.5 .5],'--k','linewidth',1.5,'handlevisibility','off')
hold on
plot(panelA(6:end,:),...
    ':o','Color',[.5 .5 .5],...
    'linewidth',1,...
    'markerfacecolor',[.5 .5 .5],...
    'markeredgecolor','w',...
    'markersize',10)

plot(mean(panelA(6:end,:),2),'-o','Color','k','HandleVisibility','off',...
    'linewidth',2.5,...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',15)

ylim([0 1])
xlim([.5 7.5])

set(gca,...
    'tickdir','out',...
    'layer','top',...
    'box','off',...
    'linewidth',2,...
    'fontsize',14);
xlabel('Session','fontsize',16)

% panel B
subplot(3,3,[4:6])
hold on
text(-.01, 1.1, 'B.','fontsize',32)

plot([0.5 25.5],[.5 .5],'--k','linewidth',1.5,'handlevisibility','off')
plot(panelB,...
    ':o','Color',[.5 .5 .5],...
    'linewidth',1,...
    'markerfacecolor',[.5 .5 .5],...
    'markeredgecolor','w',...
    'markersize',10)

plot(mean(panelB,2),'-o','Color','k','HandleVisibility','off',...
    'linewidth',2.5,...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',15)

ylim([0 1])
xlim([.5 25.5])

set(gca,...
    'tickdir','out',...
    'layer','top',...
    'box','off',...
    'linewidth',2,...
    'fontsize',14);

xlabel('Session', 'fontsize',16)
ylabel('Correct choices', 'fontsize',16) 

% panel C
subplot(3,3,7)
hold on
text(-.01, 77, 'C.','fontsize',32)

plot([4 4],[0 100],'-k','linewidth',1.5,'handlevisibility','off')
plot([1:3], panelC(:,1:3),':o',...
    'color',[.5 .5 .5],...
    'handlevisibility','off',...
    'linewidth',1.5,...
    'markerfacecolor',[.5 .5 .5],...
    'markeredgecolor','w',...
    'markersize',10)

plot([1:3],mean(panelC(:,1:3)),'-o','Color','k','HandleVisibility','off',...
    'linewidth',2.5,...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',15)

plot([5:7], panelC(:,4:6),':o',...
    'color',[.5 .5 .5],...
    'handlevisibility','off',...
    'linewidth',1.5,...
    'markerfacecolor',[.5 .5 .5],...
    'markeredgecolor','w',...
    'markersize',10)

plot([5:7],mean(panelC(:,4:6)),'-o','Color','k','HandleVisibility','off',...
    'linewidth',2.5,...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',15)
 
ylim([0 70])
xlim([.5 7.5])

set(gca,...
    'tickdir','out',...
    'layer','top',...
    'box','off',...
    'linewidth',2,...
    'fontsize',14);
xtickangle(45)
text(1, 65, 'first session','fontsize',14)
text(4.5, 65, 'last session','fontsize',14)
xticks([1 2 3 4 5 6])
xticklabels({'beginning','middle','end', 'beginning','middle','end'})

ylabel('Initiation time (s)', 'fontsize',16) 
xlabel('Session epoch', 'fontsize',16)

% panel D
subplot(3,3,8)
hold on
text(-.01, 7.7, 'D.','fontsize',32)

plot([2.5 2.5],[0 10],'-k','linewidth',1.5,'handlevisibility','off')
plot([1:2],panelD(:,1:2),':o','Color',[.5 .5 .5],...
    'linewidth',1,...
    'markerfacecolor',[.5 .5 .5],...
    'markeredgecolor','w',...
    'markersize',10)

plot([1:2],mean(panelD(:,1:2)),'-o','Color','k','HandleVisibility','off',...
    'linewidth',2.5,...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',15)

plot([3:4],panelD(:,3:4),':o','Color',[.5 .5 .5],...
    'linewidth',1,...
    'markerfacecolor',[.5 .5 .5],...
    'markeredgecolor','w',...
    'markersize',10)

plot([3:4],mean(panelD(:,3:4)),'-o','Color','k','HandleVisibility','off',...
    'linewidth',2.5,...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',15)

ylim([0 7])
xlim([.5 4.5])

set(gca,...
    'tickdir','out',...
    'layer','top',...
    'box','off',...
    'linewidth',2,...
    'fontsize',14);

xticks([1 2 3 4])
xtickangle(45)
xticklabels({'S+First', 'S+Last','S-First', 'S-Last'})

ylabel('Response time (s)', 'fontsize',16) 
xlabel('Session', 'fontsize',16)

% panel E
firstSessionChoices = panelE(1:24,:);
lastSessionChoices = panelE(25:end,:);

meanChoiceFirst(:,1) = mean(firstSessionChoices(1:8,:))';
meanChoiceFirst(:,2) = mean(firstSessionChoices(9:16,:))';
meanChoiceFirst(:,3) = mean(firstSessionChoices(17:24,:))';

meanChoiceLast(:,1) = mean(lastSessionChoices(1:8,:))';
meanChoiceLast(:,2) = mean(lastSessionChoices(9:16,:))';
meanChoiceLast(:,3) = mean(lastSessionChoices(17:24,:))';


subplot(3,3,9)
hold on
text(-.01, 1.2, 'E.','fontsize',32)

plot([4 4],[0 1.2],'-k','linewidth',1.5,'handlevisibility','off')
plot([1:3], meanChoiceFirst,':o',...
    'color',[.5 .5 .5],...
    'handlevisibility','off',...
    'linewidth',1.5,...
    'markerfacecolor',[.5 .5 .5],...
    'markeredgecolor','w',...
    'markersize',10)

plot([1:3],mean(meanChoiceFirst),'-o','Color','k','HandleVisibility','off',...
    'linewidth',2.5,...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',15)

plot([5:7], meanChoiceLast,':o',...
    'color',[.5 .5 .5],...
    'handlevisibility','off',...
    'linewidth',1.5,...
    'markerfacecolor',[.5 .5 .5],...
    'markeredgecolor','w',...
    'markersize',10)

plot([5:7],mean(meanChoiceLast),'-o','Color','k','HandleVisibility','off',...
    'linewidth',2.5,...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'markersize',15)

ylim([0 1.1])
xlim([.5 7.5])
set(gca,...
    'tickdir','out',...
    'layer','top',...
    'box','off',...
    'linewidth',2,...
    'fontsize',14);
yticks([0 .25 .5 .75 1])
xticks([1 2 3 4 5 6 7])
xticklabels({'beginning','middle', 'end', ' ' 'beginning','middle','end'})
ylabel('Correct choices', 'fontsize',20) 
xlabel('Session epoch', 'fontsize',20)
ylabel('Correct choices', 'fontsize',20) 
xtickangle(45)
text(1, .15, 'first session','fontsize',14)
text(4.8, .15, 'last session','fontsize',14)